### ISSUE TITLE
Zoom buttons flip

### ISSUE THREAD

**Issue by thkruz** [ajmas/StuffInSpace#25]
If you zoom out eventually the camera zooms back in automatically and then the buttons do the opposite of what they are labeled as (zoom out goes in and zoom in goes out).

**Comment by ajmas** [comment]
Thanks for opening an issue there. I ran into that issue the other day when demoing to a friend. I am not quite sure what going on, so will need to see why this is breaking.

**Comment by ajmas** [comment]
The base issue is that the camera doesn't seem to like negative zooms.

I have looked at adding zoom limits, but I am noticing a desync between scroll-wheel zooming and HUD zoom controls. I can decrease the zoom levels with the zoom buttons, but then the scroll-wheel things it is stuck on some zoom limit and won't scroll.

Other times, if I scroll with the scroll-wheel and then try with the on-screen buttons, then the zoom levels don't correspond. I am going to have to dig further to understand what's going on. It is likely I am using the API incorrectly.

**Comment by thkruz** [comment]
To sync those two zoom options I disabled the built in dolly (zoom) controls and had both the wheel and the buttons reference the same code now. There is a targetZoom that the user changes and then on each render loop the camera automatically zooms towards the target from its current location. Both the target and the current zoom are clamped. All zoom variables are read only at the top for easy changing later.
