### ISSUE TITLE
Non-Group Objects Pickable 

### ISSUE THREAD

**Issue by thkruz** [ajmas/StuffInSpace#27]
When selecting a group like the glonass group I am still able to select objects outside of the group from the canvas. Nothing inherently wrong with this, but it is not in line with the original design of filtering out non-group satellites. It looks like we are still calculating the pickability but it is getting dropped in updateSatellitesMaterial.

**Comment by ajmas** [comment]
I agree this is not ideal.

The quickest solution would be in `setSelectedSatellites` to ignore any indexes that fall outside of the selected group?

**Comment by ajmas** [comment]
Resolved
