### ISSUE TITLE
Selected Orbit Buffer Removed During On Hover Event

### ISSUE THREAD

**Issue by thkruz** [ajmas/StuffInSpace#37]
If you select a satellite it creates a green hover orbit line, but as soon as the on hover event is fired it removes that line. Original functionality is to have the selected orbit remain visible until a new orbit is selected or the user selects clicks empty space (satellite id -1), at which point the buffer should be cleared.

**Comment by ajmas** [comment]
Ooh that's a bug.

Playing with the UI I see that the selected satellite stays green even when the highlighted line gets removed, suggesting the issue is in the Orbits class.

**Comment by ajmas** [comment]
Resolved
