### ISSUE TITLE
Pinch to zoom issues

### ISSUE THREAD

**Issue by ajmas** [ajmas/StuffInSpace#4]
When testing on an iPhone the pinch to zoom appears to misbehave. We should explore what is causing the behaviour issues and provide a fix.

**Comment by ajmas** [comment]
While I haven't resolved this, talking with some other devs, we may get this functionality for free if we convert to three.js, but will need to play a bit to validate this.

**Comment by thkruz** [comment]
I would encourage you to explore converting to three.js if you're long term ambition is to make this accessible to other developers. I have spent years rewriting this code and there are so many hurdles that can be easily avoided by making the switch now (meshes, drawing lines, better camera controls, easy addon shaders, post processing effects,...just to name a few lol).

**Comment by ajmas** [comment]
Problem resolved as part of moving to threejs
