### ISSUE TITLE
Pinch-to-zoom broken

### ISSUE THREAD

**Issue by ajmas** [ajmas/StuffInSpace#49]
It looks like the new camera controls now breaks the pinch to zoom functionality on mobile. We should look into what needs to be done to re-introduce this for mobile and desktops that support this functionality.

**Comment by thkruz** [comment]
I didn't realize you had added that functionality (looks like it comes by default with three). Personal opinion, why don't we reintroduce the built in camera controls and just remove the buttons? 9 years after the original came out I think it is safe to say everyone has a phone with touch controls if they can get WebGl to load.

This would free up some screen real estate too.

**Comment by ajmas** [comment]
I’m okay with removing for now the zoom buttons, though creating a ticket to address the functionality of zoomIn() and zoomOut() in a future, low priority ticket.

**Comment by thkruz** [comment]
Note: The scroll wheel/pinch functions in threejs do not change the zoom values, they change the camera's position. 

This is not an issue, unless you don't know that and can't figure out why the zoom value isn't updating...
