### ISSUE TITLE
Resources don't resolve properly if URL path does not end with '/'

### ISSUE THREAD

**Issue by ajmas** [ajmas/StuffInSpace#61]
In dev, there seems to be an issue whereby if the the URL doesn't end with  `/' then resource fail to load. For example:

http://localhost:5173/StuffInSpace

To work around this issue, we should redirect to http://localhost:5173/StuffInSpace/ (with the '/'), but also ensure the query string is included. This is should be added to the top level index.ts

**Comment by thkruz** [comment]
This can be closed. (Making notes for myself).
